image:
  tag: 4.0.0

replicas: 8

comet:
  iris:
    tokenEndpoint: https://keycloak.example.domain.com/auth/realms/<realm>/protocol/openid-connect/token
    clientId: eventstore
    clientSecret: changeme
  
  cache:
    serviceDNS: horizon-callback-cache-discovery-headless.horizon.svc.cluster.local

  callback:
    redeliveryThreadpoolSize: 100

  kafka:
    consumingPartitionCount: 4
    consumerThreadpoolSize: 512
    consumerQueueCapacity: 1024
    maxPollRecords: 512

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 200Mi