image:
  tag: 4.0.0

replicas: 8

galaxy:
  kafka:
    consumingPartitionCount: 4

  cache:
    serviceDns: horizon-galaxy-cache-discovery-headless.horizon.svc.cluster.local

resources:
  limits:
    cpu: 1
    memory: 1.5Gi
  requests:
    cpu: 0.5
    memory: 200Mi