image:
  tag: 4.0.0

replicas: 8

kafka:
  broker: horizon-kafka.horizon:9092

mongo:
  url: mongodb://user:pass@horizon-mongodb-sharded.horizon.svc.cluster.local:27017
  flushIntervalSec: 5

resources:
  limits:
    cpu: 1.5
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 200Mi