apiVersion: v1
kind: ServiceAccount
metadata:
  name: horizon
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-subscriptions
  namespace: platform
rules:
  - apiGroups:
    - subscriber.horizon.telekom.de
    resources:
    - subscriptions
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: horizon-manage-subscriptions
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-subscriptions
subjects:
  - kind: ServiceAccount
    name: rover
    namespace: platform