apiVersion: v1
kind: Service
metadata:
  name: horizon-callback-cache-discovery-headless
  labels:
    app.kubernetes.io/name: horizon-essentials
    app.kubernetes.io/part-of: pubsub
spec:
  selector:
    app.kubernetes.io/part-of: pubsub
    eni.telekom.de/component: callback
  ports:
  - name: discovery
    port: 5701
    protocol: TCP
  publishNotReadyAddresses: true
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: horizon-galaxy-cache-discovery-headless
  labels:
    app.kubernetes.io/name: horizon-essentials
    app.kubernetes.io/part-of: pubsub
spec:
  selector:
    app.kubernetes.io/part-of: pubsub
    app.kubernetes.io/name: horizon-galaxy
  ports:
  - name: discovery
    port: 5701
    protocol: TCP
  publishNotReadyAddresses: true
  clusterIP: None
