apiVersion: subscriber.horizon.telekom.de/v1
kind: Subscription
metadata:
  name: 4ca708e09edfb9745b1c9ceeb070aacde42cf02f
  namespace: platform
spec:
  subscription:
    callback: http://cosmoparrot.platform/callback
    deliveryType: callback
    payloadType: data
    publisherId: eventstore
    subscriberId: eventstore
    subscriptionId: 4ca708e09edfb9745b1c9ceeb070aacde42cf02f
    trigger: {}
    type: test.event.v1