# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

listeners:  
  client:    
    containerPort: 9092    
    protocol: PLAINTEXT    
    name: CLIENT    
    sslClientAuth: ""